services:
  jellyfin-duplicate:
    image: raymice/jellyfin-duplicate:latest
    container_name: jellyfin-duplicate
    ports:
      - "8080:8080"
    environment:
      - JELLYFIN_URL=${JELLYFIN_URL}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - JELLYFIN_ADMIN_USER_ID=${JELLYFIN_ADMIN_USER_ID}
    restart: unless-stopped
